channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pyyaml=5.3.1
  - scanpy=1.4.6
  - leidenalg=0.7.0
  - louvain=0.6.1
  - plotnine=0.6.0
  - harmonypy=0.0.4
  - scrublet=0.2.1
  - dask-ml=1.2.0
  - dask-jobqueue=0.7.1
  - joblib=0.14.1
  - scikit-learn=0.22.2.post1
  - r-seurat=3.1.4
  - r-optparse=1.6.4
  - r-data.table=1.12.8
  - r-optparse=1.6.4
  - r-hdf5r=1.3.2
