channels:
  - letaylor
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pyyaml=5.3.1
  - pandas=1.0.5
  - scipy=1.5.0
  - scanpy=1.5.1
  - scikit-learn=0.23.1
  - pytorch=1.5.1
  - torchvision=0.6.1
