channels:
  - pytorch
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anndata=0.7.3
  - blas=2.16
  - blosc=1.19.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - cudatoolkit=10.1.243
  - cycler=0.10.0
  - decorator=4.4.2
  - descartes=1.1.0
  - docutils=0.16
  - flit=2.3.0
  - flit-core=2.3.0
  - freetype=2.10.2
  - get_version=2.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=64.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - joblib=0.16.0
  - jpeg=9d
  - kiwisolver=1.2.0
  - kneed=0.6.0
  - ld_impl_linux-64=2.34
  - legacy-api-wrap=1.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm8=8.0.1
  - libpng=1.6.37
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - llvm-openmp=10.0.0
  - llvmlite=0.32.1
  - lz4-c=1.9.2
  - lzo=2.10
  - matplotlib-base=3.2.2
  - mizani=0.7.1
  - mkl=2020.1
  - mock=4.0.2
  - natsort=7.0.1
  - ncurses=6.1
  - networkx=2.4
  - ninja=1.10.0
  - numba=0.49.1
  - numexpr=2.7.1
  - numpy=1.17.5
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - palettable=3.3.0
  - pandas=1.0.5
  - patsy=0.5.1
  - pillow=7.2.0
  - pip=20.1.1
  - plotnine=0.7.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytables=3.6.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytoml=0.1.21
  - pytorch=1.5.1
  - pytz=2020.1
  - pyyaml=5.3.1
  - readline=8.0
  - requests=2.24.0
  - requests_download=0.1.2
  - scanpy=1.5.1
  - scikit-learn=0.23.1
  - scipy=1.5.0
  - seaborn=0.10.1
  - seaborn-base=0.10.1
  - setuptools=48.0.0
  - setuptools-scm=4.1.2
  - setuptools_scm=4.1.2
  - six=1.15.0
  - sqlite=3.32.3
  - statsmodels=0.11.1
  - tbb=2020.1
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toml=0.10.1
  - torchvision=0.6.1
  - tornado=6.0.4
  - tqdm=4.47.0
  - umap-learn=0.4.6
  - urllib3=1.25.9
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - alabaster==0.7.12
    - babel==2.8.0
    - cellbender==0.1
    - future==0.18.2
    - imagesize==1.2.0
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - opt-einsum==3.2.1
    - pyro-api==0.1.2
    - pyro-ppl==1.3.1
    - snowballstemmer==2.0.0
    - sphinx==3.1.1
    - sphinx-argparse==0.2.5
    - sphinx-autodoc-typehints==1.11.0
    - sphinx-rtd-theme==0.5.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-programoutput==0.16
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4

