channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - yaml=0.1.7
  - scanpy=1.4.6
  - leidenalg=0.7.0
  - louvain=0.6.1
  - harmonypy=0.0.4
  - r-base=3.6.2
  - r-renv=0.9.3
