sample_qc:
    description: 'Parameters for sample QC prior to merge.
        Filters are applied to all samples.'
    cell_filters:
        description: 'Cell filters applied to each sample. Cells passing these
            filters are kept. Note: n_genes_by_counts == n_detected_features.'
        value:
            - 'pct_counts_in_top_100_genes < 50'
            - 'pct_counts_mito_gene < 80 and n_genes_by_counts > 100'
            - 'n_genes_by_counts > 2000'
    downsample_cells_fraction:
        description: 'Downsample to this fraction of the number of
            observations (sc.pp.subsample). Use "" to indicate no downsampling.
            Example: if 0.8, will drop 20% of cells.'
        value: ''
    downsample_cells_n:
        description: 'Downsample to this number of observations
            (sc.pp.subsample). Use "" to indicate no downsampling. Example: if
            200 then 200 total cells will be kept.'
        value: ''
    downsample_feature_counts:
        description: 'Downsample the number of feature counts by this fraction.
            Use "" to indicate no downsampling.'
        value: ''
plots_qc:
    description: 'Parameters for basic QC plots after sample merge. All
        pairwise combinations of facet_columns and
        variable_columns_distribution_plots will be performed.'
    facet_columns:
        description: 'Column to facet all QC plots by.'
        value:
            - ''
            - 'experiment_id,lane'
    variable_columns_distribution_plots:
        description: 'Plot the distributions of these variables (histogram and
            ecdf).'
        value:
            - 'pct_counts_in_top_100_genes'
            - 'total_counts,pct_counts_mito_gene'
reduced_dims:
    description: 'Parameters for dimensionality reduction (principal component
        and harmony calculations). All pairwise combinations of
        vars_to_regress and n_dims will be performed.'
    vars_to_regress:
        description: 'Comma seperated string of variables to regress. Use "" to
            indicate no regssion is to be performed.'
        value:
            - ''
            - 'total_counts,pct_counts_mito_gene'
    n_dims:
        description: 'Number of dimensions to use for calculating PCs,
            harmony corrected PCs, and clusters.'
        value:
            - 3
            - 30
harmony:
    description: 'Parameters for harmony.'
    variables_and_thetas:
        description: 'Tuples of metadata columns and corresponding thetas.'
        value:
            - variable: 'experiment_id'
              theta: '1.0'
            - variable: 'experiment_id,ack_lysis_buffer'
              theta: '1.0,0.2'
lisi:
    description: 'Parameters for Local Inverse Simpsons Index (LISI).'
    variables:
        description: 'Metadata variables to compute LISI over.'
        value: 'sanger_sample_id,ack_lysis_buffer'
cluster:
    description: 'Parameters for clustering. All pairwise combinations of
        method and resolution will be performed.'
    number_neighbors:
        description: 'Number of neighbors. If <= 0, uses number of unqiue
            experiment_id.'
        value:
            - 15
    methods:
        description: 'Clustering method. Valid options [leiden|louvain].'
        value:
            - 'leiden'
            - 'louvain'
    resolutions:
        description: 'Clustering resolution.'
        value:
            - 1.0
            - 3.0
cluster_validate_resolution:
    description: 'Parameters for cluster resolution validation.'
    train_size_cells:
        description: 'Number of cells to use for training. Set to -1 for
            to use defualt of 2/3 of total cells.'
        value:
            - -1
            - 1000
    sparsity:
        description: 'LogisticRegression sparsity or inverse of regularization
            strength; must be a positive float. Like in support vector
            machines, smaller values specify stronger regularization.'
        value:
            - 0.1
            - 0.01
cluster_marker:
    description: 'Parameters for identifying cluster marker features.'
    methods:
        description: 'Method for marker detection.'
        value:
            - 'wilcoxon'
            - 'logreg'
umap:
    description: 'Parameters for umap.'
    colors_quantitative:
        description: 'Comma separated string of quantitative variables that
            will be used to color points.'
        value: 'total_reads,pct_counts_mito_gene'
    colors_categorical:
        description: 'Comma separated string of categorical variables that
            will be used to color points.'
        value: 'experiment_id'
    n_neighbors:
        description: 'Number of neighbors for sc.pp.neighbors call.
            Recommended value between 2-100. If you expect each cell type
            cluster to be shared across all experiments/samples, then setting
            this number to the number of experiments/samples is a good place to
            start. Note: values separated with a comma will be run within the
            same script call (rather than swarm).'
        value:
            - 15
            - 25
            - 50
    umap_init:
        description: 'How to initialize the low dimensional embedding.'
        value:
            - 'X_pca'
            - 'spectral'
    umap_min_dist:
        description: 'The effective minimum distance between embedded points.
            Recommended value between 0-1. Note: values separated with a comma
            will be run within the same script call (rather than swarm).'
        value:
            - 0.0
            - 0.5
            - 1.0
    umap_spread:
        description: 'The effective scale of embedded points.
            Recommended value between 0-3. Note: values separated with a comma
            will be run within the same script call (rather than swarm).'
        value:
            - 0.5
            - 1.0
            - 2.5
