channels:
  - letaylor
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - pandas=1.0.5
  - scipy=1.5.0
  - scanpy=1.5.1
  - plotnine=0.7.0
  - scikit-learn=0.23.1
  - joblib=0.15.1
  - tensorflow-gpu=2.2.0
  - pip
  - pip:
      - diffxpy==0.7.4
