anndata_cell_label:
    description: 'Anndata cell label column in obs slot.'
    value: 'cluster'
differential_expression:
    condition:
        description: 'Differential condition (e.g., disease status).'
        value:
            - 'condition'
    covariates:
        description: 'Comma separated string of covariates. Enter different
            covariates for each dash to evaluate multiple covariates
            seperately.'
        value:
            - 'normalization_factor'
            - 'normalization_factor,age'
    diffxpy_method:
        description: 'Diffxpy method to use'
        value:
            - 'wald'
