anndata_cell_label:
    description: 'Anndata cell label column in obs slot.'
    value: 'cluster'
differential_expression:
    diffxpy_method:
        run_process: true
        description: 'Diffxpy method(s) to use.'
        value:
            - 'wald'
    mast_method:
        run_process: true
        description: 'MAST method to use.'
        value:
            - 'bayesglm'
    models:
        description: 'List of differential conditions (e.g., disease status)
            along with covariates. Covariates should be a comma separated
            string of covariates. Enter different covariates for each dash
            to evaluate the effect multiple covariates seperately. Size factors
            are automatically calculated and do not need to  be included. For
            no covariates use - "".'
        value:
            - variable: 'sex'
              covariate_discrete: ''
              covariate_continuous: ''
            - variable: 'sex'
              covariate_discrete: ''
              covariate_continuous: 'age'
            - variable: 'sex'
              covariate_discrete: 'id_run'
              covariate_continuous: 'age,lane'
    plot_config:
        mean_expression_filter:
            description: 'For comparison plots, drop genes whose mean
                expression for a group in anndata_cell_label is < this value.
                Example: if gene A expression is 0 counts in cluster 1 and 10
                in cluster 2, it will be dropped from cluster 1 but not cluster
                2.'
            value:
                - 0.0
                - 0.25
    rna_enrich:
        description: 'List of differential parameters to run RNA enrich on.'
        value:
            - pval_cutoff: 1
              database: 'KEGG'
              min_counts: 0
