anndata_cell_label:
    description: 'Anndata cell label column in obs slot.'
    value: 'cluster'
differential_condition:
    description: 'Differential condition (e.g., disease status).'
    value:
        - 'cd_status'
covariates:
    description: 'Differential condition (e.g., disease status).'
    value:
        - 'normalization_factor'
